version: "3"

services:
  db:
    container_name: db
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ABSOLUTE_URI: ${PHP_MY_ADMIN_ABSOULUTE_URI}

  wordpress:
    container_name: devedu.rs
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_ROOT_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      STAGING: ${STAGING}
      DHPARAM_SIZE: ${DHPARAM_SIZE}
      RSA_KEY_SIZE: ${RSA_KEY_SIZE}
      ELLIPTIC_CURVE: ${ELLIPTIC_CURVE}
      USE_ECDSA: ${USE_ECDSA}
      RENEWAL_INTERVAL: ${RENEWAL_INTERVAL}
      DEBUG: ${DEBUG}
    depends_on:
      - wordpress
      - phpmyadmin
      - next
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d

  next:
    image: "markokrizan/devedu:next"
    links:
      - wordpress:api.devedu.rs
    container_name: next
    depends_on:
      - wordpress

volumes:
  db_data:
  nginx_secrets:
