version: "3"

services:
  db:
    container_name: db
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    networks:
      - wpsite

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - wpsite

  wordpress:
    container_name: wordpress
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_ROOT_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - wpsite

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      STAGING: ${STAGING}
      DHPARAM_SIZE: ${DHPARAM_SIZE}
      RSA_KEY_SIZE: ${RSA_KEY_SIZE}
      ELLIPTIC_CURVE: ${ELLIPTIC_CURVE}
      USE_ECDSA: ${USE_ECDSA}
      RENEWAL_INTERVAL: ${RENEWAL_INTERVAL}
      DEBUG: ${DEBUG}
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./devedu_conf.d:/etc/nginx/devedu_conf.d

  next:
    network_mode: "host"
    image: "markokrizan/devedu:next"
    depends_on:
      - wordpress

networks:
  wpsite:

volumes:
  db_data:
  nginx_secrets:
