version: "3"

services:
  db:
    container_name: db
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ABSOLUTE_URI: ${PHP_MY_ADMIN_ABSOULUTE_URI}

  wordpress:
    # wpgraphql plugin needs to match wordpress site uri -> container name needs to match uri as because it is used as a resolvable name within the docker network
    container_name: devedu-test.rs
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    volumes: ["./backend:/var/www/html"]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_ROOT_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  next:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    container_name: next
    volumes:
      - ./frontend:/app
    depends_on:
      - wordpress

  nginx:
    image: nginx
    volumes:
      - ./local.conf:/etc/nginx/conf.d/devedu-test.conf
    ports:
      - "80:80"
    depends_on:
      - wordpress
      - phpmyadmin
      - next
    environment:
      DEBUG: 1

volumes:
  db_data:
